### PR TITLE
Broken references in Encrypted Media Extensions

### LINKED ISSUE #502: Broken references in Encrypted Media Extensions
While crawling [Encrypted Media Extensions](https://w3c.github.io/encrypted-media/), the following links to other specifications were detected as pointing to non-existing anchors, which should be fixed:
* [ ] https://heycam.github.io/webidl/#dfn-present
* [ ] https://www.w3.org/TR/secure-contexts/#secure-context

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

### PR DESCRIPTION
**Pull request by gregwfreedman**
Fixing non-existing anchors

Closes #502

***
<a href="https://pr-preview.s3.amazonaws.com/gregwfreedman/encrypted-media/pull/505.html" title="Last updated on Jul 19, 2023, 10:47 PM UTC (859a7c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/encrypted-media/505/9e777de...gregwfreedman:859a7c9.html" title="Last updated on Jul 19, 2023, 10:47 PM UTC (859a7c9)">Diff</a>

### CODE REVIEW

**Comment by gregwfreedman** [comment]
Similar issue happened in WebAudio. Discussion: https://github.com/WebAudio/web-audio-api/pull/2348

File: encrypted-media.js [hunk 1]
```diff
@@ -409,7 +409,7 @@
           EME_spec_url = prefix + file;
           groupBaseURLs[x] = EME_spec_url;
           // Refer to the Web IDL Editor’s Draft from Editor’s Drafts of this spec.
-          IDL_spec_url = "https://heycam.github.io/webidl/";
+          IDL_spec_url = "https://www.w3.org/TR/WebIDL-1/";
```
Comment (tidoust) [inline encrypted-media.js:412]: This URL is just a redirect to the WHATWG spec, better use the final URL directly. W3C no longer publishes the Web IDL spec in particular.

```suggestion
          IDL_spec_url = "https://webidl.spec.whatwg.org/";
```

File: encrypted-media-respec.html [hunk 2]
```diff
@@ -674,7 +674,7 @@ <h3><dfn>Navigator</dfn> Extension: <code>requestMediaKeySystemAccess()</code></
               Otherwise, it is resolved with a new <a>MediaKeySystemAccess</a> object.
             </p>
             <div class="note">
-              <p>This method is only exposed to <a href="https://www.w3.org/TR/secure-contexts/#secure-context">secure contexts</a> [[SECURE-CONTEXTS]] as indicated by the <code>[SecureContext]</code> IDL attribute.</p>
+              <p>This method is only exposed to <a href="https://www.w3.org/TR/secure-contexts/">secure contexts</a> [[SECURE-CONTEXTS]] as indicated by the <code>[SecureContext]</code> IDL attribute.</p>
```
Comment (tidoust) [inline encrypted-media-respec.html:677]: Actual definition of the secure context" concept is in HTML and can be reached through `[=secure contexts=]` in Respec (and the reference to the Secure Contexts spec could actually be dropped):

```suggestion
              <p>This method is only exposed to [=secure contexts=] as indicated by the <code>[SecureContext]</code> IDL attribute.</p>
```

**Review by tidoust — COMMENTED** [review]
I note that the spec uses a now outdated mechanism to handle cross-references. Latest version of Respec should provide many cros-references out of the box (although not all, because the spec links to concepts that are internal to HTML). I'm happy to refresh the spec once missing features have been integrated. This would make it easier to spot outdated links.

File: encrypted-media.js [hunk 3]
```diff
@@ -408,8 +408,6 @@
           var prefix = is_registry_file ? "../../" : "";
           EME_spec_url = prefix + file;
           groupBaseURLs[x] = EME_spec_url;
-          // Refer to the Web IDL Editor’s Draft from Editor’s Drafts of this spec.
-          IDL_spec_url = "https://webidl.spec.whatwg.org/";
```
Comment (gregwfreedman) [inline encrypted-media.js]: @tidoust I updated all the spec URL's, so I think this is unnecessary. Do you agree?

Comment (tidoust) [reply encrypted-media.js]: Not sure what you mean by "unnecessary"? The goal of the update was to avoid a redirect and use the right URL for Web IDL directly, which we try to do in all specs.

Comment (gregwfreedman) [reply encrypted-media.js]: @tidoust **IDL_spec_url** is already defined on line 5 of encrypted-media.js and I updated that to point to [https://webidl.spec.whatwg.org/](https://webidl.spec.whatwg.org/), so lines 411-412 are unnecessary.

**Review by joeyparrish — APPROVED** [review]

File: encrypted-media.js (hunk 3 above)
Comment (tidoust) [reply encrypted-media.js]: Ok, sounds good then!

**Review by tidoust — APPROVED** [review]
